# app/schemas/enums.py
from enum import Enum

class SessionStatus(str, Enum):
    INITIATED = "INITIATED"
    SYMPTOMS_ANALYZED = "SYMPTOMS_ANALYZED"
    ANALYZING_BODY = "ANALYZING_BODY"
    BODY_MATCHED = "BODY_MATCHED"
    GENERATING_RECOMMENDATIONS = "GENERATING_RECOMMENDATIONS"
    RECOMMENDATIONS_READY = "RECOMMENDATIONS_READY"
    OPTION_SELECTED = "OPTION_SELECTED"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    TIMEOUT = "TIMEOUT"
    ABANDONED = "ABANDONED"